print(True)
print(False)
print(1.3 + 2)
print("Texto com aspas")
print('Texto comm aspas simples')
print('Vocês são ' + 3 * 'top ' + 'demais')
print([1, 2, 3])
print({"nome": "Rodrigo", "idade": 23, 10: "id", True: "verdadeiro"})
print(None)